//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChartToJson.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Plugins_ImportAllPluginsOnStartup {
            get {
                return ((bool)(this["Plugins_ImportAllPluginsOnStartup"]));
            }
            set {
                this["Plugins_ImportAllPluginsOnStartup"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Must select an entity or press \"Cancel\" button.")]
        public string Texts_NoEntitySelected {
            get {
                return ((string)(this["Texts_NoEntitySelected"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LastFileLoadedPath {
            get {
                return ((string)(this["LastFileLoadedPath"]));
            }
            set {
                this["LastFileLoadedPath"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("You are about to create an empty new file. Do you want to save your current file?" +
            "")]
        public string NewFileConfirmationMessage {
            get {
                return ((string)(this["NewFileConfirmationMessage"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("The file contains one or more \"ResourceDictionary\" plugins that are not currently" +
            " loaded:")]
        public string OpenFileErrorMessage_ResourceDictionaryPluginNotFound {
            get {
                return ((string)(this["OpenFileErrorMessage_ResourceDictionaryPluginNotFound"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("There were an error trying to load the file with path \"$\".")]
        public string OpenFileErrorMessage_General {
            get {
                return ((string)(this["OpenFileErrorMessage_General"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("The file contains one or more \"IChartEntityViewModel\" plugins that are not curren" +
            "tly loaded:")]
        public string OpenFileErrorMessage_VMPluginNotFound {
            get {
                return ((string)(this["OpenFileErrorMessage_VMPluginNotFound"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LastImageExportedPath {
            get {
                return ((string)(this["LastImageExportedPath"]));
            }
            set {
                this["LastImageExportedPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LastJsonExportedPath {
            get {
                return ((string)(this["LastJsonExportedPath"]));
            }
            set {
                this["LastJsonExportedPath"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Export to JSON file")]
        public string ExportToJSONDialogTitle {
            get {
                return ((string)(this["ExportToJSONDialogTitle"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Export to image file")]
        public string ExportToImageDialogTitle {
            get {
                return ((string)(this["ExportToImageDialogTitle"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Flow chart to Json")]
        public string MainWindowTitlePrefix {
            get {
                return ((string)(this["MainWindowTitlePrefix"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1900")]
        public double DefaultCanvasWidth {
            get {
                return ((double)(this["DefaultCanvasWidth"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("800")]
        public double DefaultCanvasHeight {
            get {
                return ((double)(this["DefaultCanvasHeight"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("You are about to open a saved file. Do you want to save your current file?")]
        public string OpenFileConfirmationMessage {
            get {
                return ((string)(this["OpenFileConfirmationMessage"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("CONTENT")]
        public string MEFPluginTemplatesKeysString_Content {
            get {
                return ((string)(this["MEFPluginTemplatesKeysString_Content"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SHAPE")]
        public string MEFPluginTemplatesKeysString_Shape {
            get {
                return ((string)(this["MEFPluginTemplatesKeysString_Shape"]));
            }
            set {
                this["MEFPluginTemplatesKeysString_Shape"] = value;
            }
        }
    }
}
