//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChartCanvasNamespace.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
    internal sealed partial class ToolTips : global::System.Configuration.ApplicationSettingsBase {
        
        private static ToolTips defaultInstance = ((ToolTips)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new ToolTips())));
        
        public static ToolTips Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Toggle to connect to other entities creating a connection, or to change one end o" +
            "f an existing connection. Maintain shift to show resizing and rotating thumbs")]
        public string ToolTips_EntityConnectingThumb {
            get {
                return ((string)(this["ToolTips_EntityConnectingThumb"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Drag and Drop to move Entity. Maintain shift to show resizing and rotating thumbs" +
            "")]
        public string ToolTips_EntityMovingThumb {
            get {
                return ((string)(this["ToolTips_EntityMovingThumb"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Toggle to connect to an Entity through an Entity Connecting Thumb")]
        public string ToolTips_LineConnecter {
            get {
                return ((string)(this["ToolTips_LineConnecter"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Connection between two entities")]
        public string ToolTips_LineConnection {
            get {
                return ((string)(this["ToolTips_LineConnection"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Press to divide this Connection line in two segments")]
        public string ToolTips_LineDivider {
            get {
                return ((string)(this["ToolTips_LineDivider"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Drag and Drop to move this end of the two segments of this line")]
        public string ToolTips_LineDragger {
            get {
                return ((string)(this["ToolTips_LineDragger"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Drag and Drop to move Entity. Release shift to show connecting and moving thumbs")]
        public string ToolTips_EntityResizingThumb {
            get {
                return ((string)(this["ToolTips_EntityResizingThumb"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Drag and Drop to rotate Entity. Double click to reset angle. Release shift to sho" +
            "w connecting and moving thumbs")]
        public string ToolTips_EntityRotatingThumb {
            get {
                return ((string)(this["ToolTips_EntityRotatingThumb"]));
            }
        }
    }
}
