//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChartCanvasNamespace.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
    internal sealed partial class UndoRedoNames : global::System.Configuration.ApplicationSettingsBase {
        
        private static UndoRedoNames defaultInstance = ((UndoRedoNames)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new UndoRedoNames())));
        
        public static UndoRedoNames Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Split line connection")]
        public string LineConnection_DivideSegment {
            get {
                return ((string)(this["LineConnection_DivideSegment"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Remove line connection segment")]
        public string LineConnection_RemoveSegment {
            get {
                return ((string)(this["LineConnection_RemoveSegment"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Remove line connection")]
        public string LineConnection_Remove {
            get {
                return ((string)(this["LineConnection_Remove"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Move entity")]
        public string EntityBorder_Move {
            get {
                return ((string)(this["EntityBorder_Move"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Move line connection entity")]
        public string LineConnection_MoveLineDragger {
            get {
                return ((string)(this["LineConnection_MoveLineDragger"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Connec entities with line connection")]
        public string LineConnection_CreateLine {
            get {
                return ((string)(this["LineConnection_CreateLine"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Reconnect line connection end")]
        public string LineConnection_ReconnectLine {
            get {
                return ((string)(this["LineConnection_ReconnectLine"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Resize entity")]
        public string EntityBorder_Resize {
            get {
                return ((string)(this["EntityBorder_Resize"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Rotate entity")]
        public string EntityBorder_Rotation {
            get {
                return ((string)(this["EntityBorder_Rotation"]));
            }
        }
    }
}
